// <auto-generated />
using LAB2_WITHOUTMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LAB2_WITHOUTMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220510211309_2fws")]
    partial class _2fws
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LAB2_WITHOUTMVC.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Sporty wodne",
                            Description = "Łódka przeznaczona dla jednej osoby",
                            Name = "Kajak",
                            Price = 275m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Sporty wodne",
                            Description = "Chroni i dodaje uroku",
                            Name = "Kamizelka ratunkowa",
                            Price = 48.95m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Piłka nożna",
                            Description = "Zatwierdzone przez FIFA rozmiar i waga",
                            Name = "Piłka",
                            Price = 19.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
