version: '3.4'

services:
  sportsstore:
    build: .
    ports:
      - "7983:5267"
    depends_on:
      - sqlserver
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      
      SA_PASSWORD: "MyDatabaseSecret123"
      ACCEPT_EULA: "Y"
